version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8876:80"
    depends_on:
    - app
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www